service: facebook-ingestion

provider:
  name: aws
  region: ${self:custom.env.aws_region_name}
  stage: ${opt:stage}
  deploymentBucket:
    name: ${self:custom.env.code_bucket}
    maxPreviousDeploymentArtifacts: 5

custom:
  env: ${file(./env/${self:provider.stage}.yml)}

Glue:
  bucketDeploy: ${self:custom.env.code_bucket}
  s3Prefix: ${self:custom.env.code_prefix}/${self:custom.env.job_name}_${self:provider.stage}/
  tempDirBucket: ${self:custom.env.code_bucket}
  tempDirS3Prefix: ${self:custom.env.code_prefix}/temp

  jobs:
    - name: ${self:custom.env.job_name}_${self:provider.stage}
      scriptPath: ./facebook_ingest.py
      tempDir: true
      type: pythonshell
      glueVersion: python3-1.0
      role: !Ref GlueRole
      MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 45
      DefaultArguments:
        class: GlueApp
        extraPyFiles: ${self:custom.env.whl_wr},${self:custom.env.whl_facebook_sdk}
        customArguments:
          secret_name: ${self:custom.env.secret_name}
          data_bucket: ${self:custom.env.data_bucket}
      SupportFiles:
        - local_path: ../libraries
          s3_bucket: ${self:custom.env.code_bucket}
          s3_prefix: ${self:custom.env.code_prefix}/${self:custom.env.job_name}_${self:provider.stage}/libraries/
          execute_upload: True # => You can set it as `False` to speed up the deployment if there are no updates to the libraries
  triggers:
    - name: Weekends Facebook Ingestion
      schedule: 0 10 ? * SAT-SUN *
      actions:
        - name: ${self:custom.env.job_name}_${self:provider.stage}
          args:
            secret_name: ${self:custom.env.secret_name}
            data_bucket: ${self:custom.env.data_bucket}
    - name: Weekdays Facebook Ingestion
      schedule: 0 7-19/3 ? * MON-FRI *
      actions:
        - name: ${self:custom.env.job_name}_${self:provider.stage}
          args:
            secret_name: ${self:custom.env.secret_name}
            data_bucket: ${self:custom.env.data_bucket}

plugins:
    - serverless-glue

# AWS resources
resources: ${file(./partials/resources.yml)}
