Resources:
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:provider.stage}-${self:service}-GlueRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: ${self:provider.stage}-${self:service}-GluePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                  - s3:ListBucketMultipartUploads
                Resource: 
                  - "arn:aws:s3:::${self:custom.env.data_bucket}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - "arn:aws:s3:::${self:custom.env.data_bucket}/intake/*"
              - Effect: Allow
                Action:
                  secretsmanager:GetSecretValue
                Resource:
                  - "arn:aws:secretsmanager:eu-west-1:000000000000:secret:${self:custom.env.secret_name}"
