Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic
      TopicName: ${self:provider.stage}-${self:service}-Error

  SNSSubscription1:
    Type: AWS::SNS::Subscription
    Properties:
        Endpoint: ${self:custom.subscription_endpoint_01}
        Protocol: email
        TopicArn: {"Ref": "SNSTopic"}

  # Make Glue database
  GlueDatabase: # TODO/FEAT: Move this to a general infrastructure setup repository
    Type: AWS::Glue::Database
    Properties:
      CatalogId: ${aws:accountId}
      DatabaseInput:
        Name: ${self:custom.env.glue_database_name}

  # Glue Role for facebook-ingestion
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:provider.stage}-${self:service}-GlueRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: ${self:provider.stage}-${self:service}-GluePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                  - s3:ListBucketMultipartUploads
                Resource:
                  - arn:aws:s3:::${self:custom.env.data_bucket}
                  - arn:aws:s3:::${self:custom.env.code_bucket}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::${self:custom.env.data_bucket}/intake/*
                  - arn:aws:s3:::${self:custom.env.data_bucket}/metadata/*
                  - arn:aws:s3:::${self:custom.env.code_bucket}/${self:custom.env.code_prefix}/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${self:custom.env.fb_secret_name}*
