job_name: facebook_ingestion
code_bucket: example-code-s3-bucket-name
code_prefix: glue-code/scripts
secret_name: accessToken-appId-appSecret-businessId/facebookApi/ingestion
data_bucket: example-data-s3-bucket-name
aws_region_name: eu-west-1
