partition_by_account_id: True # If true add account_id to partitions
table_version: 'V1'
field_keys:
  ad_insights:
    - date_start
    - date_stop
    - account_id
    - account_name
    - ad_id
    - ad_name
    - adset_id
    - adset_name
    - campaign_id
    - campaign_name
    - reach
    - impressions
    - clicks
    - frequency
    - cost_per_outbound_click
    - outbound_clicks
    - spend
  ad:
    - id
    - adset_id
    - campaign_id
    - account_id
    - configured_status
    - creative
    - effective_status
    - priority
    - date_format
    - execution_options
    - name
    - updated_time
    - created_time
    - status
    - targeting
  ad_set:
    - id
    - account_id
    - adset_schedule
    - billing_event
    - budget_remaining
    - campaign_id
    - configured_status
    - created_time
    - effective_status
    - end_time
    - start_time
    - status
    - name
    - lifetime_budget
    - updated_time
  campaign:
    - id
    - account_id
    - budget_remaining
    - buying_type
    - can_use_spend_cap
    - configured_status
    - created_time
    - daily_budget
    - name
    - effective_status
    - objective
    - pacing_type
    - start_time
    - status
    - stop_time
    - updated_time
  ad_image:
    - id
    - account_id
    - creatives
    - hash
    - name
    - permalink_url
    - status
    - updated_time
