partition_by_account_id: True # If true add account_id to partitions
table_version: 'V1'
field_keys:
  campaign:
    - name
    - budget_remaining
    - lifetime_budget
    - start_time
    - status
    - effective_status
    - objective
    - buying_type
    - created_time
    - stop_time
  ad_set:
    - billing_event
    - bid_strategy
  ads:
    - id
    - name
    - creative
    - status
    - configured_status
    - effective_status
    - updated_time
    - bid_amount
    - ad_review_feedback
    - tracking_specs
    - source_ad
    - preview_shareable_link
    - recommendations
    - issues_info
    - conversion_domain
  ad_creatives:
    - image_url
    - image_hash
    - link_url
    - object_url
    - thumbnail_url
    - status
    - name
    - body
    - instagram_permalink_url
    - link_destination_display_url
    - url_tags
  ad_insights:
    - optimization_goal
    - cpc
    - cpm
    - cpp
    - account_currency
    - account_name
    - clicks
    - impressions
    - ctr
    - objective
    - spend
    - reach
